echo "mkdir -p /root/.ssh && chmod 700 /root/.ssh"
TYPE=dsa
if [ -f ~/.ssh/id_rsa ]; then
    TYPE=rsa
fi
echo "if [ ! -e /root/.ssh/github_$TYPE ]; then"
echo "  cat <<EOF> /root/.ssh/github_$TYPE"
echo "$(cat ~/.ssh/id_$TYPE)"
echo "EOF"
echo "  cat <<EOF>> /root/.ssh/config"
echo "StrictHostKeyChecking no"
echo "Host github.com"
echo "    User git"
echo "    IdentityFile ~/.ssh/github_$TYPE"
echo "EOF"
echo "  chmod 600 /root/.ssh/*"
echo "  fi"
echo "if [ ! -e /home/zenoss/.ssh/github_$TYPE ]; then"
echo "  cat <<EOF> /home/zenoss/.ssh/github_$TYPE"
echo "$(cat ~/.ssh/id_$TYPE)"
echo "EOF"
echo "  cat <<EOF>> /home/zenoss/.ssh/config"
echo "StrictHostKeyChecking no"
echo "Host github.com"
echo "    User git"
echo "    IdentityFile ~/.ssh/github_$TYPE"
echo "  "
echo "EOF"
echo "  chown zenoss:zenoss /home/zenoss/.ssh/github_$TYPE"
echo "  chmod 600 /home/zenoss/.ssh/github_$TYPE"
echo "fi"
echo "which easy_install > /dev/null 2>&1 || wget -O- https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python"
echo "which pip > /dev/null 2>&1 || wget -O- https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python"
echo "pip install -e /home/zenoss/zendev"
echo "systemctl enable mysqld.service && systemctl start mysqld.service"
echo "systemctl enable redis.service && systemctl start redis.service"
echo "systemctl enable rabbitmq-server.service && systemctl start rabbitmq-server.service"
echo "systemctl enable hbase.service && systemctl start hbase.service"
echo "systemctl enable opentsdb.service && systemctl start opentsdb.service"
echo "for i in 1 2 3 4 5; do"
echo "    sleep 2"
echo "    rabbitmqctl status >/dev/null 2>&1 && break"
echo "    systemctl restart rabbitmq-server.service"
echo "done"   
echo "rabbitmqctl add_user zenoss zenoss"
echo "rabbitmqctl add_vhost /zenoss"
echo "rabbitmqctl set_permissions -p /zenoss zenoss '.*' '.*' '.*'"
echo "/opt/opentsdb/src/create_table.sh"
