echo "mkdir -p /root/.ssh && chmod 700 /root/.ssh"
TYPE=dsa
if [ -f ~/.ssh/id_rsa ]; then
    TYPE=rsa
fi
echo "if [ ! -e /root/.ssh/github_$TYPE ]; then"
echo "  cat <<EOF> /root/.ssh/github_$TYPE"
echo "$(cat ~/.ssh/id_$TYPE)"
echo "EOF"
echo "  cat <<EOF>> /root/.ssh/config"
echo "StrictHostKeyChecking no"
echo "Host github.com"
echo "    User git"
echo "    IdentityFile ~/.ssh/github_$TYPE"
echo "EOF"
echo "  chmod 600 /root/.ssh/*"
echo "  fi"
echo "if [ ! -e /home/zenoss/.ssh/github_$TYPE ]; then"
echo "  cat <<EOF> /home/zenoss/.ssh/github_$TYPE"
echo "$(cat ~/.ssh/id_$TYPE)"
echo "EOF"
echo "  cat <<EOF>> /home/zenoss/.ssh/config"
echo "StrictHostKeyChecking no"
echo "Host github.com"
echo "    User git"
echo "    IdentityFile ~/.ssh/github_$TYPE"
echo "  "
echo "EOF"
echo "  chown zenoss:zenoss /home/zenoss/.ssh/github_$TYPE"
echo "  chmod 600 /home/zenoss/.ssh/github_$TYPE"
echo "fi"
echo "which easy_install > /dev/null 2>&1 || wget -O- https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python"
echo "which pip > /dev/null 2>&1 || wget -O- https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python"
echo "pip install -e /home/zenoss/zendev"
